### create product
POST http://localhost:8080/api/products
X-Api-Key: SECRET
Content-Type: application/json
Accept: application/json

{
  "id" : "A0004",
  "name" : "Sendal Jepit",
  "price" : 60000000,
  "quantity" : 1
}


### get product API
GET http://localhost:8080/api/products/A0001
X-Api-Key: SECRET
Accept: application/json

### get product API (SALAH)
GET http://localhost:8080/api/products/A00a01
X-Api-Key: SECRET
Accept: application/json



### update product API )
PUT http://localhost:8080/api/products/A0001
Content-Type: application/json
Accept: application/json

{
  "name" : "Macbook pro 2015 murah",
  "price" : 123,
  "quantity" : 2
}

### update product API (SALAH)
PUT http://localhost:8080/api/products/A0001
Content-Type: application/json
Accept: application/json

{
  "name" : "Macbook pro 2015 murah meriah",
  "price" : 123,
  "quantity" : 3
}



### DELETE
DELETE http://localhost:8080/api/products/A00010
Accept: application/json



### List product API
GET http://localhost:8080/api/products
X-Api-Key: SECRET
Accept: application/json


### List product API With size parameter
GET http://localhost:8080/api/products?size=2
Accept: application/json

### List product API With size and page parameter
GET http://localhost:8080/api/products?size=2&page=1
X-Api-Key: SECRET
Accept: application/json



