### create product
POST http://localhost:8080/api/products
Content-Type: application/json
Accept: application/json

{
  "id" : "A0002",
  "name" : "Macbook pro 2019",
  "price" : 60000000,
  "quantity" : 1
}


### get product API
GET http://localhost:8080/api/products/A0001
Accept: application/json

### get product API (SALAH)
GET http://localhost:8080/api/products/A00a01
Accept: application/json



### update product API )
PUT http://localhost:8080/api/products/A0001
Content-Type: application/json
Accept: application/json

{
  "name" : "Macbook pro 2015 murah",
  "price" : 123,
  "quantity" : 2
}

### update product API (SALAH)
PUT http://localhost:8080/api/products/A0001
Content-Type: application/json
Accept: application/json

{
  "name" : "Macbook pro 2015 murah meriah",
  "price" : 123,
  "quantity" : 3
}



### DELETE
DELETE http://localhost:8080/api/products/A00010
Accept: application/json



### List product API
GET http://localhost:8080/api/products
Accept: application/json



